### ISSUE TITLE
"Issueベース開発"レビュー依頼

### ISSUE THREAD

**Issue by ichi-being** [ichi-being/floss-buddy#39]
### 実装予定の機能
- [ ] LINEログイン
- [ ] LINE通知機能
- [ ] 楽天検索API
- [ ] フロス実施記録に応じた応答メッセージの変化
- [ ] ユーザーのグループ化
### 必要なページ
- [ ] トップページ
- [ ] ユーザープロフィール
- [ ] フロス実施履歴表示
- [ ] フロスの有効性
- [ ] フロスの種類と選び方、やり方動画
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ

**Comment by Tsuchiya2** [comment]
LGTMです
