### ISSUE TITLE
MVPリリースレビュー依頼

### ISSUE THREAD

**Issue by ichi-being** [ichi-being/floss-buddy#67]
## 各種情報
サービス名　Floss Buddy
サービスURL　https://floss-buddy.fly.dev/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] LINEログイン機能
- [ ] 初期プロフィールの登録（フロス実施状況）
- [x] LINEリッチメニューを用いてトーク画面上で実施記録をつける
- [x] 実施記録に対する画像付き応答メッセージ
- [x] 週一回の振り返り通知（LINE Messaging API）
- [x] 記録途切れのときの画像の変化

## READMEレビュー時から変更した機能
* 初期プロフィールの登録（フロス実施状況）は、初期登録時のフロス実施状況に応じて最初のポイントを変えようかと思ってましたが、あまり意味がないかと思って実装はやめました。
* プロフィール画面のドラフト版を作成し、アカウント削除機能をつけました。ただ、LINEのLIFFブラウザでログインした状態でChromeなどのLIFFブラウザ以外のブラウザ上でアカウント削除はされないようお願いします。LIFFブラウザでセッションが削除されず、LIFFブラウザはキャッシュを削除できないので、user_idが残ってしまい、もう一度ユーザー登録をできない事態が発生しました。LIFFブラウザで開いたときのみ、アカウント削除ボタンが出るように実装する予定です。

## サービスイメージがわかるようなスクリーンショット等
操作はスマホのLINE上で行うことを前提としています。

* 友達登録後のLINE画面。ここのURLを踏んでもらい、ユーザー登録する。
[![Image from Gyazo](https://i.gyazo.com/f837a4f95f1e17341b35063e6980ed17.png)](https://gyazo.com/f837a4f95f1e17341b35063e6980ed17)

* トーク上でのフロス実施入力。フロス実施連続日数により、応答画像が変化します。応答メッセージも節目で送られます。
[![Image from Gyazo](https://i.gyazo.com/e07ada1695413d6c2218d49c94759d90.png)](https://gyazo.com/e07ada1695413d6c2218d49c94759d90)
* 同じ日の日付の登録が行われないように制限をかけています。保存できないこともトーク上で返します。
[![Image from Gyazo](https://i.gyazo.com/c4998341bf9fb122fc04137c57420b7c.png)](https://gyazo.com/c4998341bf9fb122fc04137c57420b7c)

* 週一回のリマインド通知と３日坊主忘れ対策通知のsidekiq設定およびメッセージ。
* ３日坊主忘れのメッセージはレビュー提出前に条件に沿ってLINE上に実行できてないので画像がありません(３日間空ける前に次の記録をつけてしまい、通知をもらい損ねました)。
[![Image from Gyazo](https://i.gyazo.com/95f1d47ca1d8fbd577acb2361af0e289.png)](https://gyazo.com/95f1d47ca1d8fbd577acb2361af0e289)
[![Image from Gyazo](https://i.gyazo.com/b6fdbff76e23e01e17cbc60ee1043f00.png)](https://gyazo.com/b6fdbff76e23e01e17cbc60ee1043f00)

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
以下、コメントになります。

LINEから「フロスの記録をつける」を選択すると`昨日` `今日`の選択肢が表示されるかと思うのですが、その後、選択できないようでした。
こちら一度調査していただいてよろしいでしょうか？（本番環境のログを見る等）
私の端末の問題の可能性もあるので、もし、本番環境でも動いていそうであれば、そちらのGIF等を添付していただけるとありがたいです。

**Comment by ichi-being** [comment]
ご確認ありがとうございました。
fly logsコマンドやflyのダッシュボードで確認しようと思ったのですが、富田講師の行った時間のログまで遡ることができませんでした。
一応、妻のLINEで「フロス記録をつける」を実行したときのLINE画面のGIFと、fly logsのスクリーンショットを添付させていただきます。

* LINE画面のGIF
![20240206_124252](https://github.com/ichi-being/floss-buddy/assets/130316386/0a33c1fc-7a66-45af-91dd-7f65d5d05964)



* ログのスクリーンショット
[![Image from Gyazo](https://i.gyazo.com/bbfe078bf7090a0e43cb08c6b9d45c79.png)](https://gyazo.com/bbfe078bf7090a0e43cb08c6b9d45c79)

**Comment by ichi-being** [comment]
同期に試してもらったところ、友達登録後のあいさつメッセージのURLが間違っており、404エラーとなっていました。

正しいURLに変更し、ユーザー登録とログインが成功することを確認しました。フロス記録の登録もでき、プロフィールページも表示されるようになっています。

**Comment by Tsuchiya2** [comment]
私も挙動確認しましたが、LINEから「フロスの記録をつける」後に出る"昨日" "今日"の選択肢が押せませんでした。
もう一度調査をいただけますでしょうか？

**Comment by ichi-being** [comment]
@Tsuchiya2 
土屋講師、ご確認ありがとうございます。

念のため確認なのですが、あいさつメッセージに載せているURLからアカウント登録はされていますでしょうか？

データベースのログを見ると、floss_recordsに保存する際にuser_idがnullとなっており、エラーとなっていました。

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
